#version should be only changed with RELEASE eminent, see RELEASE.md

version: 2.8.0-ci-{build}

image: Visual Studio 2019

clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

init:
  - ps: |
      git config --global core.autocrlf input
      
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        $ver = $env:APPVEYOR_REPO_TAG_NAME
        if($ver.StartsWith("v") -eq $true) { $ver = $ver.Substring(1) }
        Update-AppveyorBuild -Version $ver
      }

environment:
  matrix:
    - BUILD_TARGET: base
    - BUILD_TARGET: fsharp

build_script:
- cmd: dotnet build src/CommandLine/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% /p:BuildTarget=%BUILD_TARGET%

test_script: 
- cmd: dotnet test tests/CommandLine.Tests/ /p:BuildTarget=%BUILD_TARGET%

after_test:
- cmd: dotnet pack src/CommandLine/ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% /p:BuildTarget=%BUILD_TARGET%

artifacts:
- path: 'src/CommandLine/bin/Release/*.nupkg'
  name: NuGetPackages
- path: 'src/CommandLine/bin/Release/*.snupkg'
  name: symbol 
  
on_failure:
- cmd: |
    tree /f /a >files.lst
    appveyor PushArtifact .\files.lst -DeploymentName "Failed Build File Listing"

deploy:
- provider: GitHub
  auth_token:
    secure: hVyVwHl0JiVq0VxXB4VMRWbUtrGclIzadfnWFcWCQBLvbgMLahLBnWlwGglT63pZ
  artifact: /.*(\.|\.s)nupkg/
  prerelease: false
  force_update: true #fsharp package runs as separate build job, so have to force_update to add fsharp.nuget added
  on:
    APPVEYOR_REPO_TAG: true

- provider: NuGet
  api_key:
    secure: e2gJJ3r6Uls5trJwryaudAZd49QniNfIjax/A+tfywlchSnIQVOzOQCO9tTSNccI
  artifact: /.*(\.|\.s)nupkg/
  on:
    APPVEYOR_REPO_TAG: true
